### ISSUE TITLE
Is there support for random write at a particular offset for block blob?

### ISSUE THREAD

**Issue by raintears** [Azure/azure-storage-java#104]
I can't seem to find the documentation on it. Please help. Thanks!

**Comment by asorrin-msft** [comment]
No, there isn't - block blobs aren't really designed for random-write.  You can re-order and add/remove whole blocks at a time - see the API's uploadBlock(), downloadBlockList(), and commitBlockList().  When you call downloadBlockList(), the size of each block is returned, so you could use this to mimic a limited random-write feature.

If random-write is more important to you than re-ordering data, I recommend using page blobs instead of block blobs.  Page blobs need to be precreated at a fixed size, before any data is written.  Once created, they support random write of any page (or set of pages).  A page is 512 bytes, so you can't directly write to any byte offset, but this is handled by downloading the page that contains the byte(s) you want to overwrite, overwriting the data, and then writing back the modified page.
Will this work for you?
