### ISSUE TITLE
API GW Configuration

### ISSUE THREAD

**Issue by ronnelson929** [Azure/azure-storage-java#114]
I have a requirement to send all cloud service calls through an api gateway. Based on the way the signature string is constructed we've run into issues correctly signing the auth string since the url is used as part of the signature. If I use the path of our gateway, the signature request fails. 

I've tried changing my host file and then certificate verification fails on an https call because it's not calling the microsoft service directly. 

Is there a way to create the calls and signature against the correct blob storage endpoint but send the request through a different endpoint? It doesn't seem that using a proxy works because it doesn't allow for using a specific URL address only a server name. I might be missing something, but it doesn't seem like the sdk is prepared for this use case, has anyone else had a similar use case?

**Comment by mirobers** [comment]
The signature does not depend on endpoint. It depends on the account name, resource path, and the URI query. Do you actually want to modify the path of the URL? Could you give an example of what you want the URL to be on the wire versus what URL you want to sign against?

**Comment by ronnelson929** [comment]
I want to leave the path as the sdk calls it but I want to send my request to <someserver>.<mydomain>.com</someendpoint>.  The gateway would forward the request on to the appropriate url for getting a blob or listing all the containers etc.

**Comment by mirobers** [comment]
Sending the request to someserver.mydomain.com can be done by explicitly specifying this endpoint in your connection string. However, placing "someendpoint" in the path won't work because the storage service uses the URL path as part of its own protocol. If you can't preserve the original path then you'll need to use your own protocol and implement wrapping and unwrapping of the original URL as it passes through your service.
