### ISSUE TITLE
Should TableEntity and its decedents specify Map<String,EntityProperty> instead of HashMap<String,EntityProperty>

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-storage-java#12]
https://github.com/Azure/azure-sdk-for-java/issues/323

**Comment by 64BitChris** [comment]
The argument for changing the libraries to return the interface is that Map is Java idiomatic for libraries to return rather than a specific implementation type. 

The pain is mostly felt by the methods which take HashMap as an argument from the clients.  Most Java developers will pass around an instance of Map rather than HashMap.  When we encounter these SDK methods, clients have to convert their Map into a HashMap - which has no functional benefit because all the SDK needs is a class which conforms to the Map interface (ie. put/get).

**Comment by shtratos** [comment]
+1 to what Chris says!

You can provide method overloads that accept `Map` instead of `HashMap` in order not to break existing clients.
Then mark `HashMap`-accepting methods as `@Deprecated` and announce that they will be removed in next major version release.

**Comment by emgerner-msft** [comment]
We'd honestly love to do that. It annoys me to, and I agree it's much more idiomatic to return an interface. If I were writing this library from scratch, I'd do it that way -- no question! Here's the problem: 

The readEntity method which takes a HashMap has an equivalent writeEntity method which returns a HashMap.If we take Map, we can't return HashMap. There isn't an easy deprecation strategy for getters the way there are setters since we can't make an overload named the same but with a different return type. We can take a break, but most folks hate breaks and there isn't an incredibly functional reason for this one besides style. We still debated this break, but looking at the number of changes we needed in the tests (albeit simple changes) we concluded we might upset more people than we made happy by making the change.

**Comment by shtratos** [comment]
Thank you for detailed reply!

Actually, in Java world accepting parameters of wider type while returning implementation type is considered perfectly normal. 
By accepting an interface, you state that your method is applicable to any object implementing that interface.
By returning implementation class, you give guarantees to clients on how the result behaves.

For example:
If you return `HashMap` from the method, your clients can assign it to either `Map` or `HashMap` as they wish. But they can expect that result is non-thread-safe and lookups are O(1)-amortised.
On the other hand, if you accept `HashMap` in the method params, your clients are bound to pass `HashMap` or its descendants only. You can't pass, say, `ConcurrentHashMap`, so clients are forced to make a copy.

At our codebase we often have methods like:
```
public ImmutableList<String> capitalizeAll(Iterable<String> strings);
```
Here we guarantee to the clients that the result will be [ImmutableList](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ImmutableList.html): immutable and thus safe to use in concurrent environment. At the same time, clients can pass any Iterable (e.g. Set or Queue) as method input.

**Comment by emgerner-msft** [comment]
I completely understand that. 

However, in several of the implementations what is set is actually related to what is returned. If you take a look at DynamicTableEntity (for example) there are getProperties and setProperties methods. These both deal in HashMaps at the moment. They are also related to readEntity and writeEntity as in this case those methods simply return the properties. So, if I change readEntity to take a Map, that calls setProperties under the covers. So, I also change setProperties to take a Map. Then the type of properties has to change to a Map (since I can't guarantee it's a HashMap) and both getProperties and writeProperties must now return Maps as well.

**Comment by shtratos** [comment]
Can't you just make a change to `setProperties` to do a protective copy?

```
public void setProperties(final Map<String, EntityProperty> properties) {
        this.properties = new HashMap<>(properties);
}
```

**Comment by emgerner-msft** [comment]
That was another consideration. The issue with that is performance. I could very well be wrong, but from what I researched this is relatively memory intensive. With larger sized entities or a larger number of entities the concern was that this would be quite a hit. If you have numbers which show otherwise at scale I'd be curious to see though.

**Comment by shtratos** [comment]
So I did a quick JMH benchmark with a small map:
https://gist.github.com/shtratos/4ac95bc0de3ce411c782

```
Result: 10237418.092 ±(99.9%) 60083.276 ops/s [Average]
  Statistics: (min, avg, max) = (9319293.762, 10237418.092, 10803978.259), stdev = 254396.352
  Confidence interval (99.9%): [10177334.816, 10297501.367]

# Run complete. Total time: 00:13:31

Benchmark                      Mode  Cnt           Score          Error  Units
Benchmarks.measureAssignment  thrpt  200  1540347529.233 ± 11465572.425  ops/s
Benchmarks.measureCopy        thrpt  200    10237418.092 ±    60083.276  ops/s
```

So HashMap copy takes about 97 *nanoseconds* on my laptop (CPU - 2.3 GHz Intel Core i7)
(Simple assignment takes about 1 ns)
So client code will be slower by 1 millisecond for every ~10,000 of entities created/updated.

IMHO this is negligible.

**Comment by shtratos** [comment]
If you like, I can put the benchmark on github, so you can run it yourself.

**Comment by emgerner-msft** [comment]
Thanks for looking at this and posting the benchmark! 

It doesn't shock me that for small entities this is the result. Looking at the numbers I see it's a 100x increase though with an even larger increase in variance. I realize that if it's 100x and the first number was small then it's fine, but that kind of increase for larger entities (whether larger map or larger values) is where I'd be concerned:

1. Entities can support up to 252 properties (in addition to partition key, row key, and timestamp. Each entity can be up to 1MB in size.
2. Tables frequently have thousands of entities, so this needs to run a lot more times. At scale this is the kind of throughput that would be seen, so the total increase is important.
3. In addition to CPU, we also need to examine memory increase which was the original concern.
4. Max time (or 99%tile). I see the variance increased a lot. If this would make some operations occasionally really slow, that's also worth considering.

I can spend some time and modify the code you posted to account for those concerns sometime next week, though if you're curious it looks like you're a pro at the benchmarking tooling already. :) If we can show for larger entities we don't see significant CPU or memory increase copy is a doable change.

**Comment by shtratos** [comment]
Thanks for the numbers! I'll see if I have bandwidth to create benchmarks for worst case.

Re 3. HashMap copy is shallow, so memory overhead should not be big.
Re 4: p999 is 10177334 operations per second, which is ~98.2 ns per operation.

**Comment by shtratos** [comment]
So I put the benchmark for something that might resemble real entities here:
https://github.com/shtratos/java-benchmarks/blob/master/src/main/java/com/github/shtratos/benchmarks/HashMapBenchmark.java#L61

You can run them on your machine, feel free to tweak the settings.
(e.g. increase number of iterations to bring the error interval down)
See README for instructions.

I've got the following results for `throughput` measurements:
```
Benchmark                                   Mode  Cnt         Score         Error  Units
HashMapBenchmark.measureHashMapCopy        thrpt   25    525324.865 ±   36855.562  ops/s
HashMapBenchmark.measureTreeMapCopy        thrpt   25    632723.419 ±   27457.889  ops/s
HashMapBenchmark.measureSmartCopyBadCase   thrpt   25    486658.441 ±   88172.254  ops/s
HashMapBenchmark.measureSmartCopyGoodCase  thrpt   25  72698353.454 ± 2313061.419  ops/s
HashMapBenchmark.measureAssignment         thrpt   25  81712783.711 ± 8906990.064  ops/s
```
Absolute numbers are very different from last time, because I ran benchmarks concurrently and with fewer iterations to avoid waiting 30 minutes for them to complete. You can run them with default settings, that should give you better estimates.

Note the `smartCopyProperties` method: 
```
        public void smartCopyProperties(Map<String, String> properties) {
            if (properties instanceof HashMap) {
                this.properties = (HashMap<String, String>) properties;
            } else {
                this.properties = new HashMap<>(properties);
            }
        }
```
It adds a minuscule type-check penalty, but avoids copying if client passes in an instance of `HashMap`.
I'd say it's worth considering if you think simple copy is too expensive in general.

**Comment by emgerner-msft** [comment]
Took some time and fiddled around with this some more. I did some quick and dirty testing as well with a more integrated version (ie, with actual service calls mixed in) and it looks good to me. I think the smartCopy is a good idea. I think it's best to build on that idea and apply the copying in the getter rather than the setter. We'd store the properties as a Map and in the getter, cast to a HashMap if able before returning and otherwise set the properties to a new HashMap created from whatever other type was stored. This means we actually never have to do the copy in some implementations and in others, we only have to do it on the get.

In any case, the concern remains that this would break the interface, though not as egregiously. We've got quite a bit of time before our next breaking release (as far as I know now), so we'll ask around and see if other customers have any major issues. The folks most unhappy would most likely be those that did custom implementations where they would have to do this sort of manipulation now has well.

If folks seem generally happy or neutral towards this change we'll take it our next breaking release. Otherwise, I'll follow up on this thread.
