### ISSUE TITLE
Asynchronous call to Azure endpoint

### ISSUE THREAD

**Issue by kishore25kumar** [Azure/azure-storage-java#122]
Is there any way in Azure java sdk to asynchronously call azure endpoint. Something like async client or something? Right now the way I use the sdk the calling thread is blocked till the response comes. If there is some implementation let me know?

If it's not there is there any plan to implement it?

**Comment by rambo-msft** [comment]
Hey @kishore25kumar,
Unfortunately, there is very little language level support for asynchronous operations in our minimum supported version for us to offer this functionality. We plan to revisit this topic when we drop support for 6 and move to 7.

In order to avoid blocking, you will have to spawn a new thread for invocations. 
Look into using ``Class FutureTask<V>`` , which takes a Callable or Runnable object that can wrap the method you want to call asynchronously.

**Comment by kishore25kumar** [comment]
@rambo-msft thanks. Looking forward to that feature 👍. Let me know if I could contribute to it

**Comment by dtretyakov** [comment]
@rambo-msft, it would be great to implement async endpoints in storage library APIs same way as in the azure java sdk: https://github.com/Azure/azure-sdk-for-java

They have already get rid of Java 6 support.

Do you have some estimates when it could be available?

**Comment by rambo-msft** [comment]
Hi @dtretyakov,
Agreed.
While I cannot give you a timeline just yet, we are actively looking into the best way to offer this functionality.

**Comment by 0GiS0** [comment]
Hi @rambo-msft,

can we insert entries in a table asynchronously?

thanks

**Comment by jofriedm-msft** [comment]
@0GiS0, as mentioned above, none of our APIs support asynchronous calls yet. When this support comes we expect it to be for all APIs
