### ISSUE TITLE
retry logic cause 409 error

### ISSUE THREAD

**Issue by mogliang** [Azure/azure-storage-java#35]
Hi,

Our user use Azure storage Java SDK to operate Table storage. When there is a high level of concurrent insertion of new records to the same Azure table, sometimes the insertion fails with ‘409 Conflict’ error.

After disable sdk retry logic, 409 error disappeared. This confirms that issue is caused by retry logic, to be specific, if client side abandon request after client timeout but server side finished the transaction, then the subsequent retry request will fails due to 409 error. 

If I remember correctly, .net storage library had same issue before. As a feedback, please update java sdk to avoid such retry 409 error.

Thanks for your works!

**Comment by vinaysh-msft** [comment]
Hi @mogliang ,
The Storage client SDK has no way to confirm whether the conflict returned during insertion was caused due to the previous timeout that it hit or due to existing data already present. If your application does not care about these conflicts (for example, when it knows that it’s the only one that can insert new records), you can use [insert or replace](http://msdn.microsoft.com/en-us/library/azure/hh452242.aspx) or [insert or merge](http://msdn.microsoft.com/en-us/library/azure/hh452241.aspx) semantics to avoid getting a 409 back from the storage service during insertions. 
Another option is to provide a custom retry policy with your own business logic on when to retry on 409 error.

**Comment by mogliang** [comment]
Use Insert or replace could be a good idea.
By the way, how if let client side wait time longer than server side timeout value? will it work?

**Comment by vinaysh-msft** [comment]
Not sure I understand how client side wait time longer than server side timeout value will help here. Your best option is to use insert or replace semantics.
