### ISSUE TITLE
Performance of TransferManager upload file when file size is under 256 MB

### ISSUE THREAD

**Issue by aryalrabin** [Azure/azure-storage-java#373]
When uploading file of size less than 256 MB  using [TransferManager.uploadFileToBlockBlob](https://github.com/Azure/azure-storage-java/blob/master/src/main/java/com/microsoft/azure/storage/blob/TransferManager.java) (line 70) to Azure Blob Storage. Performance seems to be bad as the file is uploaded in one chunk (Code at line 80 ) and is also ignoring provided  TransferManagerUploadToBlockBlobOptions. Files larger than 256MB is broken into 100MB chunks and performance is better.

Here are some benchmarks  uploading to Western Europe
File size MB | Time in ms
500 | 241987
250 | 597095
257 | 277543

Was there any reason to upload a file less than 256MB in one chunk? Removing code that does a upload in single chuck will improve the performance.

**Comment by rickle-msft** [comment]
Hi, @aryalrabin. Thank you for reporting this and for taking the time to clock some uploads. There were two main reasons for this decision. The first was to save costs. As customers are billed on each transaction, we hoped to reduce the costs of uploading a blob by using as few transactions as possible. The second was scheduling. We made an effort to get the feature out so customers could make use of it with the intention of iterating on it.

So this implementation was more a philosophical choice than a deeply technical one. In fact, there is an existing item in our backlog to investigate the benefits of a more configurable upload behavior. Can you please detail what would be your ideal experience here? We were planning on adding an option or parameter to the effect of maxSingleShotSize, below which any file would be uploaded all at once, but we are happy to consider your suggestions. It sounds like perhaps you would like us to simply honor the blockSize parameter regardless of how big the file is, and the only time we ever upload entirely in one request is if the file happens to fit in one block?

Finally, you said that the options are ignored. Which options are you seeing ignored in particular? The single-shot upload is passing the headers, metadata, and accessConditions from the options. Parallelism is not used but doesn't really make sense for a single request. blockLength is ignored, but it is documented that it will be ignored for a single upload and is a parameter on the method rather than a field on the options. I just want to make sure I'm understanding the specifics of the issue so we can most fully address it. 

Thanks again!

**Comment by rickle-msft** [comment]
@aryalrabin. Thank you for the details. We will take that into consideration when designing this improvement. I will keep you posted on the status of this enhancement.

**Comment by chhajerpawan** [comment]
I am trying to upload 4 GB file using blob.upload and its taking lot for time to upload, I am getting 6MB/s speed only, Do we have any mechanism to upload large file using java sdk faster. I am also facing problem while uploading large file, due to connection reset it upload partial file, can we avoid that also

**Comment by rickle-msft** [comment]
Hi, @chhajerpawan. It is curious to me that you are only seeing 6MB/s, and it would require more investigation to understand why that is happening. For now, could you please try using the TransferManager.uploadFileToBlockBlob method (it is a static method) and let me know if that works?

There has been a lot of investigation over the past few weeks into the connection reset issue, and we should have a release coming out very soon that makes several fixes in that area, hopefully resolving this problem.

**Comment by chhajerpawan** [comment]
Thanks for quick response, Cloud you please advise which version of Azure JAVA SDK is stable, Currently I am using 8.0.0 
<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-storage</artifactId>
			<version>8.0.0</version>
		</dependency>

Looks like TransferManager is not available into this

**Comment by rickle-msft** [comment]
Woops! This post was originally about v10, which is a different architecture and where the TransferManager lives, so I assumed that's what we were discussing. Both are stable and supported. v8 is entirely synchronous whereas v10 has async offerings but also does require some work to migrate as it is a significant break.

CloudBlob also does have an uploadFromFile method. Is that what you are referring to when you say blob.upload()? If not, could you please try using the uploadFromFile method?

**Comment by chhajerpawan** [comment]
So blob.upload is taking steam as input, in my use case i am trying to transfer data from S3 to Azure Blob Storage, So getting S3 Object Stream from S3 and passing to Azure Blob blob.upload. I cannot use  uploadFromFile because it will need file and in my use case if i get data into file and then pass to azure then for large file need to store file in memory.

**Comment by rickle-msft** [comment]
@chhajerpawan Sorry for the hassle, but since this is actually a different issue from the original post, can I ask you to please create a new issue?

**Comment by rickle-msft** [comment]
@aryalrabin. We have released v11.0.0 of the SDK which includes this feature addition. Please consider upgrading and trying it out. I will close this issue now as the original post has been addressed and the follow up has been moved to a new issue. Please feel free to reopen this issue if the new release does not adequately address the feature request.
