### ISSUE TITLE
V10 support for files?

### ISSUE THREAD

**Issue by SuhanKoh** [Azure/azure-storage-java#384]
Will V10 support Azure Files Storage in the near future?

**Comment by rickle-msft** [comment]
Hi, @SuhanKoh. Thank you for your interest in the V10 Files SDK. Yes it will! It is currently in development, and we should have a preview out in a couple weeks!

**Comment by SuhanKoh** [comment]
@rickle-msft Thanks for the news. 
For the artifact id, I assume it would be azure-storage-files? separating each service?

**Comment by rickle-msft** [comment]
You are correct. Queues recently previewed as azure-storage-queues, so I strongly anticipate azure-storage-files will be the artifact id.

**Comment by svzdvdoptum** [comment]
We need Azure Files Storage support too! Any updates on a possible release date? Thanks

**Comment by rickle-msft** [comment]
We are hoping to get some more resources to continue working on getting Files out the door soon, but I can't give an exact date. We apologize that it has been stalled for a while.

**Comment by JordanMartin** [comment]
Should we use the V8 legacy version if I need to manipulate a File Service Storage ?
Have you an availability date for a release or preview version ?

**Comment by rickle-msft** [comment]
@JordanMartin Right now, yes. The preview of v10 Files is very close to being ready and has been for quite a while. Unfortunately we just have not been able to prioritize getting it out the door because of a variety of other work items that have come up. I do not have an estimated release date as of right now.

**Comment by warrenzhu25** [comment]
@rickle-msft Do you have some timeline when we can have this?

**Comment by rickle-msft** [comment]
@warrenzhu25 Unfortunately we still don't have an exact date. The reason for the delay is we have been working on the v12 for blobs, which is now released. This was an important update because it fixed a lot of the stability and usability issues that many customers encountered in v11. The consequence is that files and queues have been delayed, though they should not be far behind.

**Comment by rickle-msft** [comment]
As an update for everyone here, we have released a preview for files in v12. The only reason it did not GA was because of a last minute renaming of some type names that we wanted to preview first, but it should be very stable now and getting GAed soon. Please give the new version a try and let us know if you need any support. I am going to close this issue now as it has been addressed.
