### ISSUE TITLE
Breaking change of Storage blob v10 to get InputStream and OutputStream

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-storage-java#389]
We rely on InputStream and OutStream to handle file download and upload since it's standard across Java. Could you let storage blob v10 continue to support this?

**Comment by rickle-msft** [comment]
Hi, @warrenzhu25. Thank you for your question. BlobInputStream and OutputStream will not be supported in V10+. The most significant reason for this is that v10+ is asynchronous, relying on the ReactiveX implementation of ReactiveStreams. Input and OutputStreams don't really exist in this paradigm and are replaced by Flowables (well, the ReactiveStream's interface is Publisher, but RxJava implements that as Flowable). Therefore, while we do plan to offer support for critical scenarios, and indeed the TransferManager already supports file upload and download, these new implementations will necessarily look different. 

If this satisfactorily answers your question, I'll ask you to please close the issue. If you have more questions, however, please feel free to ask.

**Comment by alexander-riss** [comment]
not being able to stream a large binary from e.g a user provided request directly to a Blob is a show stopper for us.
The implementation of the Async framework should not limit the use case in such a significant way. The problem only exists since the ReactiveX framework always assumes repeatability of requests - which is not the case for streaming input/output - and is not directly related to async processing.

IMHO there should also be a way to perform streaming operations on V10 - even if they were synchronous/blocking operations - else the user base will probably split to stay on V8 forever for these use cases.

**Comment by rickle-msft** [comment]
@alexander-riss, thank you for voicing that concern. I'm in the process of implementing a method which will allow users to upload to a blob from a non-replayable flowable, which should enable support for streaming customer data directly to a blob. Because this method does not assume the Flowable is replayable, as do our other upload options, there will be some buffering involved, but it will be configurable by the user. Does this sound like it will suit your scenario?

**Comment by alexander-riss** [comment]
@rickle-msft Sounds absolutely perfect! Thank you very much for listening to user feedback!

**Comment by rickle-msft** [comment]
Sure thing! The SDK is for you guys! :)

**Comment by warrenzhu25** [comment]
What's timeline for deprecating old version of SDK?

**Comment by warrenzhu25** [comment]
We're implementing Spring Resource abstraction by using storage blob sdk. Previously, I can just return `InputStream` and `OutputStream` to user, but now we couldn't do it. Could you help how to implement this based on storage v10 sdk? https://github.com/Microsoft/spring-cloud-azure/blob/master/spring-cloud-azure-storage/src/main/java/com/microsoft/azure/spring/cloud/storage/BlobStorageResource.java

**Comment by rickle-msft** [comment]
@warrenzhu25 Regarding deprecation, plans are not set in stone. It will most likely be deprecated sometime within the next 12 months, possibly sooner, but we have not made any active moves towards an official announcement or anything.

For switching to v10, I will first recall what I mentioned earlier that the paradigms are different, so there's not a direct analogue here. RxJava is based on the idea of asynchronous, reactive streams whereas OutputStream is not inherently reactive or asynchronous. We believe it would be best for the overall architecture of your application to switch to an asynchronous model entirely as it offers quite a few performance benefits. If you aren't fond of Rx in particular, note that there are options to convert between Java Futures.

Further, in some manner of speaking, the standard download() call in v10 functions like getting an input stream to a blob would. The return type is Flowable<ByteBuffer>, which will emit ByteBuffers as the are read off the wire. It would also be possible to use the TransferManger.uploadFromNonReplayableFlowable method (in development now) as a substitute for an OutputStream. The Flowable given to this method can be of arbitrary size and behavior, so the user can write to it until they are finished, and this method will handle chunking and staging blocks automatically. 

That said, if switching to an asynchronous model all at once is too onerous, you should be able to convert between the two using the [generate](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#generate-io.reactivex.functions.Consumer-) and [create](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#create-io.reactivex.FlowableOnSubscribe-io.reactivex.BackpressureStrategy-) methods. You can see some examples on how that might work [here](https://android.jlelse.eu/i-created-a-flowable-and-i-liked-it-7ab2af54f94a). 

I hope this helps. Please let us know if you have more questions!

**Comment by pemari-msft** [comment]
We have no plans to deprecate the SDK at this time.

**Comment by rickle-msft** [comment]
Hi, @alexander-riss and @warrenzhu25, I put out v10.5.0 which includes the feature I mentioned that should enable uploading network streams to blobs: uploadFromNonReplayableFlowable. Please let us know if this meets your needs.

**Comment by kagkarlsson** [comment]
It would be helpful with an example on using `uploadFromNonReplayableFlowable` with an InputStream

**Comment by rickle-msft** [comment]
@kagkarlsson.

We are working on revamping our story around InputStream support since it has been such a common ask. In the meantime, I can work with you on meeting your needs here to unblock you. 

I would recommend you start by implementing the [Flowable interface](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html) (the only method you actually need to implement is [subscribeActual](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#subscribeActual-org.reactivestreams.Subscriber-)). In that method, you will essentially read some amount from your InputStream and then call the Subscriber's onNext method for every chunk you read.

Please let me know if you have any questions about that or if you need more support. Depending on your scenario, there may be other considerations. For instance, there are constraints that calls to onNext must be serialized, but if you aren't dealing with massive streams or any additional complexity, this implementation should work fine.

**Comment by kagkarlsson** [comment]
I think it would be a very good idea to have first-class support of InputStream/OutputStream even if it's all rxjava under the hood.

And for anyone wondering how to convert a Flowable to an InputStream, have a look at [Bytes](https://github.com/davidmoten/rxjava2-extras/blob/master/src/main/java/com/github/davidmoten/rx2/Bytes.java#L42) from rxjava2-extras.

Something like: 
```java
    public static Flowable<ByteBuffer> inputStreamAsFlowable(final InputStream is, final int bufferSize) {
        return Flowable.generate(emitter -> {
            byte[] buffer = new byte[bufferSize];
            int count = is.read(buffer);
            if (count == -1) {
                emitter.onComplete();
            } else if (count < bufferSize) {
                emitter.onNext(ByteBuffer.wrap(Arrays.copyOf(buffer, count)));
            } else {
                emitter.onNext(ByteBuffer.wrap(buffer));
            }
        });
    }
```

**Comment by rickle-msft** [comment]
@kagkarlsson Thank you for sharing this. As mentioned, we are developing a more complete story for Input/output stream support that fits within a broader context of customers still wanting to use these apis synchronously. We should have a preview of that in the next month or two if everything goes as planned. Hopefully this can hold you over in the meantime.

**Comment by landro** [comment]
@rickle-msft I can't seem to see any new commits related to the java.io.InputStream/OutputStream APIs. Could you provide us with an update on your roadmap? Do you still think the API should be ready roughly by the end of July?

**Comment by rickle-msft** [comment]
You are correct that you can't find them because they don't live here right now :). But they are under development right now as a part of some larger changes to address recurring concerns beyond just this one. There will be at least a preview of it by the end of July.

**Comment by landro** [comment]
@rickle-msft Any reason for not performing this work in the open? Seems like there is a lot of interest among users to contribute to the best possible solution (as in make sure the API actually matches user expectations).

**Comment by rickle-msft** [comment]
@landro There is a reason why it's not in the open right now, though I cannot say why at this time. Hopefully it suffices to say that it will be in the open in the next couple weeks and there will be plenty of opportunity to offer feedback and contributions before anything is set in stone. If there are particular scenarios/features/interfaces of the stream support in v8 you would like to ensure support for or request we modify, we are more than happy to take those into consideration. Broadly speaking, right now we are working to mostly forward port the way BlobInputStream and BlobOutpuStream worked in v8.

**Comment by rickle-msft** [comment]
Hi, all. Just to give you an update, this feature was added into v12. We would love for anyone here to check it out if they are so interested. I am going to close this issue now as this feature has been added back. Please feel free to reopen it if you need further support.

**Comment by jspenc4** [comment]
where is the new api for this?
