### ISSUE TITLE
MalformedURLException is wrapped in RuntimeException by the SDK

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-storage-java#409]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
10.2.0

### What problem was encountered?
If the given container or blob name leads to a MalformedURLException while creating a reference for it using the SDK, it raises a MalformedURLException wrapped in RuntimeException. It forces one to catch all unchecked exceptions to handle this particular exception. It would be good to have a checked exception for this particular error, just like in the previous version of the SDK.

**Comment by rickle-msft** [comment]
Hi, @SukruthKS. Thank you for posting this. Can you please share a stack trace?

**Comment by rickle-msft** [comment]
Oh gotcha. I'm with you now. I think Rx can in certain cases wrap errors in a RuntimeException depending on how you (mis)use it, so that's what I where I thought this was going, but this is clearly our code :)

Here's the thinking around that RuntimeException: We start with a valid URL, which is the container URL. We are adding an element which has already been sanitized (via `safeURLEncode()`) onto this valid url path. The result should invariably be a valid URL, and if it's not, then there is something seriously wrong in a way that, by our estimation, is not really recoverable by any client. Because of this thinking, we didn't want to burden customers with a checked exception type that would do nothing more than make the code more verbose as it would never be thrown in a recoverable way. Therefore, we opted to throw a RuntimeException instead. 

I am happy to continue to discuss the design of our exception handling if you feel that reasoning is unsatisfactory or flawed.

**Comment by SukruthKS** [comment]
Thanks for the explanation! Makes sense.
