### ISSUE TITLE
'take' of TableQuery didn't work

### ISSUE THREAD

**Issue by lhlyg** [Azure/azure-storage-java#41]
Here's my codes:
TableQuery<DynamicTableEntity> query =
                TableQuery.from(DynamicTableEntity.class)
                .where(TableQuery.generateFilterCondition("PartitionKey", TableQuery.QueryComparisons.GREATER_THAN_OR_EQUAL, startkey))
                        .take(recordcount);

It didn't return specific number of entities. Instead, it wrongly returned all entities which match the 'where' condition.

**Comment by emgerner-msft** [comment]
Could you include some code showing how you executed the query? Namely, did you use execute or executeSegmented and in either case, how did you iterate through elements?

**Comment by lhlyg** [comment]
Here are the codes:
CloudTable table = azureTableDB.getTableReference(tableName);
for(DynamicTableEntity entity: tableX.execute(query))
{
       resultHashMap.add(extractAttributes(entity.getProperties()));
       //extractAttributes is a method to convert entity properties to my custom dataType 
}

**Comment by emgerner-msft** [comment]
I think what you’re expecting will happen if you use executeSegmented instead of execute. executeSegmented will execute a single query to the service and return you a ResultSegment<T> with everything returned. This segment will contain up to your take count (let’s say 5, for example) responses which you can access via it’s getResults method. Note that even if there are 5 results on the service executeSegmented may return less than that and give you a continuation token which you must follow to get the rest.

execute returns an Iterable<T>. The where/select work exactly the same here, but take count doesn’t really make sense because the iterable will simply query the service for more results when you ask for more. All take count does here is ask the service only for the next 5 entities each time it asks the service for more. 

I would recommend taking a look in Fiddler to demonstrate the above points. You can see executeSegmented will only make one request whereas execute will make multiple service requests (at least for your code below). Both will correctly include the take count limit of 5 in each service request.

So, using execute is nice since it follows continuation tokens for you, but it will keep getting results as long as you keep asking for more (which currently is what your for-loop does). If you make a for-loop that only iterates over the first 5 elements that should solve your issue and stop execute from making extra requests and returning extra results. All that being said, we are thinking about changing this behavior in the future so that the Iterable<T> takes only the take count even if asked for more elements as you are not the first to be confused by this behavior.
