### ISSUE TITLE
How to generate the Authorization from a given connectionString ?

### ISSUE THREAD

**Issue by patrickmayer0** [Azure/azure-storage-java#426]
Hi,

We're basically trying to redirect an output stream (length is known) and save the content to a block blob but the sdk does not seem to offer this functionality. Both BlockBlobURL and TransferManager classes seem to use a file as the source content. We're not familiar with io.reativex

As a work around, we'd try use the blob storage REST API but are having an issue with the creation of the Authorization header value. Since the azure-storage-java sdk is actually a wrapper on REST calls, we were wondering if it was possible to generate the Authorization token.

Looks like the SharedKeyCredentials class might be used for this but it does not expose the token.   Could you provide a way to get the token or, alternately, provide an example of how to use the sdk to send a straight HTTP post to a blob storage via the REST API?

Version used: azure-storage-java sdk 10.4.0

Best regards,
Patrick

**Comment by patrickmayer0** [comment]
Note: our goal is to read from a stream, than transfer the content directly to a block blob, while keeping as little dat was possible in memory while in transit.

**Comment by rickle-msft** [comment]
Hi, @patrickmayer0. Thank you for your question and for the details. 

We currently have a feature in CR which would enable you to upload an arbitrary stream (well, Flowable) to a blob. This should enable your scenario of redirecting a network stream, or any stream of unknown length. It will have to do some internal buffering, but it will be configurable to fit your environment. I'm working on getting that out ASAP. 

Since you do know the size, depending on the size of your source, you might be able to just use BlockBlobURL.upload() directly. I know you don't know the exact size, but if you know the source to generally be small-medium, then you shouldn't get too many problems there. The danger is that if a retry is necessary, you'll get an error for reasons I can explain if you're interested. 

I don't think we will open up the SharedKeyCredentials class to expose those methods. That said, if you instantiate an instance and then use the create() method to create a policy, you can send your HttpRequest through just that one policy, which will add the Authorization header to the request. 

Let me know if you need more information on any of these options. I'm also happy to offer some support on Rx if you guys are having difficulty there.

**Comment by patrickmayer0** [comment]
Hi,
Pardon me for asking but what do you mean by "CR" ? (Under review?)  Is there a way to get this version so that we can use it? Any idea when this will be GA?

As for using  BlockBlobURL.upload() directly, we will handle streams of several megabytes in length, concurrently. Hence the reason why we insist on using streams, not finite sized ByteBuffers. As for the retry: I suppose we'd be able to refetch the data from the start if the exception pops up.

I'll keep in mind your comment about using the create() method on SharedKeyCredentials: looks like the right way to go at this point.

Thanks,
Patrick

**Comment by rickle-msft** [comment]
Sorry that's my bad. "CR" means "code review". I'll let you know when that feature is out. I can't give a definitive timeline, but I'm hoping to get it out ASAP. It really just depends on how our management sets our priorities. 

I think the upload() solution sounds like your best bet for now, although upload() also takes a Flowable as input, actually, so that looks like it'll be an obstacle in both?

**Comment by patrickmayer0** [comment]
Ok. In the meantime, we took the long road and managed to use the REST API to get the job done. Let us know when this feature is ready: it will allow us to simplify our services' code when we use it.

**Comment by rickle-msft** [comment]
@patrickmayer0 I apologize for neglecting to follow up on this earlier, but the feature I mentioned above, TransferManager.uploadFromNonReplayableFlowable should allow you to effectively upload the contents of a network InputStream to a blob in a way that considers limitations on system resources. 

If you are interested, could you give this a try and see if it meets your needs? Even if you are satisfied with simply using the REST api I would appreciate if you could either post a follow up or close the issue. Thanks!

**Comment by rickle-msft** [comment]
I am going to close this as it has been inactive for a while and we are encouraging customers to move off of v10/11 in favor of v12, which should have features to support this scenario. Please feel to reopen or comment if you need further support.
