### ISSUE TITLE
SDK V10 disable logging

### ISSUE THREAD

**Issue by julianzur** [Azure/azure-storage-java#433]
I am using the V10 SDK with Spring Boot (2.1.2). Today I upgraded from 10.2.0 to 10.4.0 just to figure out that my logs are now polluted with information that I don't need at all. I tried this:

    @Bean
    public PipelineOptions disableBlobStorageLogging() {
        return new PipelineOptions()
            .withTelemetryOptions(new TelemetryOptions(""))
            .withLoggingOptions(new LoggingOptions(15000, true))
            .withLogger(new HttpPipelineLogger() {
                @Override
                public HttpPipelineLogLevel minimumLogLevel() {
                    return HttpPipelineLogLevel.OFF;
                }

                @Override
                public void log(HttpPipelineLogLevel httpPipelineLogLevel, String s, Object... objects) {

                }
            });
    }

But it did not work because "LoggingFactory.slf4jLogger.isInfoEnabled()" in LoggingFactory returns "true". But why isn't it enough to use the LoggingOption "disableDefaultLogging"?
        
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
    compile("com.microsoft.azure:azure-storage-blob:10.4.0")
    compile("com.microsoft.azure:azure-storage-spring-boot-starter:2.1.2")

### What problem was encountered?
Logging is very hard to disable

### Have you found a mitigation/solution?
No.

**Comment by rickle-msft** [comment]
Hi, @julianzur. We are sorry that you encountered this issue and thank you for reporting it. I hope a bit of background will help illuminate what is going on here. 

Default logging is actually different from the slf4j logging. We often find that customers will contact us for support but won't be able to provide relevant information because logging has not been set up. To facilitate customer support, we have added default logging to the SDK, which will write errors to some files in the temp directory. Disabling default logging stops the sdk from writing to these files. 

Separate from default logging is slf4j logging which uses the respects the application's configuration and behaves as any other sdk that uses slf4j. It is unaffected by the disableDefaultLogging flag. If you would like to disable the logs coming from slf4j, you will have to modify the logger config file in your path. If you only want to ignore files from the Storage SDK, you should be able to filter out log entries coming from the logger "Azure Storage Java SDK", which will leave the logging for the rest of your application intact. 

I hope this helps, but please let me know if you have further questions or difficulties.

**Comment by julianzur** [comment]
Hi @rickle-msft. Thanks for your detailled feedback! I really appreciate that you took the time to answer my comment and I see your point with the "default logging". Although I don't think this is a good solution. 
Forcing everyone to use an undocumented logger is not a common pattern for Java libraries to use. If you still think this is a good idea, please update the documentation accordingdly. So users who really don't want this logger know how to disable it.
On top of that, I as a user of this library, expect it just to work. I don't neccesarrily care about the way the internal requests are structured. I want it to store and read blobs. Period. If it fails to do so and therefore detailled logging is required for analysis - then I can _enable_ debug-logging to find out what is wrong with my setup. Logging detailled information about every single call is way too much information for the "INFO" level.
And my last point: why is the logger not called by it fully qualified class name? How am I supposed to fine-tune the logger in spring boot? I know I can use something like this in my logback.xml:

    <logger name="Azure Storage Java SDK" level="off">
    </logger> 

But the standard way to use 

    logging.level.com.microsoft.azure.storage.blob.LoggingFactory=off

in the application.properties does not work. 
Can you show me how to disable the logger without changing the logback.xml?

**Comment by rickle-msft** [comment]
@julianzur. We understand that this is not a common pattern, but we have found this issue with customer support to be prevalent enough that it warranted a unique solution. We tried to make this "hidden" logging as unintrusive as possible by limiting the max size to only a few mb and keeping it all in the temp directory, so it's totally fair to just delete it. The goal was essentially that the customer didn't need to know about it until they filed a ticket and, if they didn't already have logs, customer support could point out that there are these default logs in order to unblock the support. 

If you are still not satisfied with this solution and have a more idiomatic alternative, please let me know and we will be happy to consider. Additionally, please let me know where you think would be the most visible place to document this behavior and how best to modify the documentation that would make it more clear to you what is going on. Right now, it is documented on the constructor for LoggingOptions, and the comment reads:
"By default, this library will automatically log warnings and errors to some files in the system's directory. The size of these files is bounded to a few dozen MB and should not impose a burden on the system. It is strongly recommended to leave these logs enabled for customer support reasons, but if the user desires a different logging story and enables logging via the HttpPipelineLogger or SLF4J, then it should be safe to disable default logging."

I am understanding your third point to be that INFO level logging is too verbose. This again we are happy to accept feedback on. Currently, ERROR level is for requests that fail as determined by either exceptions or network-related status codes (i.e. 503s), WARNING is for requests that may be successful but took what was determined to be an unusually long time to complete, and INFO is for everything else. What would you see as appropriate for INFO versus DEBUG?

The reason the logger is not called by it's fully qualified class name is because it seemed at the time of development that, since all logging passes through this central place in the SDK, it would be more clear if the logger was simply named after the SDK rather than a specific class in the SDK. I think we would be willing to change the name to what you have indicated is standard practice. I don't know much about spring boot, but it [looks like](https://stackoverflow.com/a/36882664) you might be able to refer to the logger by its name in the same way?

**Comment by lgaudez** [comment]
I faced the same problem with verbose logs. I had to create a logback xml file in spring boot application to avoid this. It would be nice not have "space" in the logger name so I could have set a dedicated logging property in my application property file in order to choose logging level for your library.

**Comment by rickle-msft** [comment]
@lgaudez Thank you for your feedback. We have a release coming up, and I plan to change the name of the logger to the fully qualified class name

**Comment by julianzur** [comment]
Thanks @rickle-msft. With the latest version my problem has been solved. I still don't think it is a good idea to log "debug" content with "info" loglevel - but now I can at least easily disable it.

**Comment by rickle-msft** [comment]
@julianzur. I am glad this resolves your issue!

Thank you for that feedback. I will bring this up for discussion on our team as we continue to think about the logging story across all our SDKs.

**Comment by DPICART** [comment]
I had the same issue with 10.5

I added <Logger name="Azure Storage Java SDK" level="error"/> to the log4j2.xml of my springboot app.
