### ISSUE TITLE
Azure Storage - Blob listing, no request is being made/initiated

### ISSUE THREAD

**Issue by akash-infiverve** [Azure/azure-storage-java#477]
### Which service(blob, file, queue, table) does this issue concern?
Blob Service

### Which version of the SDK was used?
Azure Storage SDK v11.0.1 for Java

### What problem was encountered?
I'm attempting the following request from two different classes (Test class and Service class)-

```
serviceURL.listContainersSegment(null, new ListContainersOptions()).blockingGet().body().containerItems().forEach(container -> {
        System.out.println("createServiceUrl | Container "+container.name());
    });
```
**Test class results**:

The request gets executed as it should and I'm getting the names of the container in my Azure storage account. The request is made and verified using Wireshark

**Service class results**:

- The request is not being made from this class, checked this using Wireshark.

- The thread gets blocked indefinitely. No request is being made(verified with wireshark) and no exception is being thrown or no other errors occur in any of the log files where logs are written.

**NOTE**: 
Service class is present as a jar and deployed as a Vertx verticle in another application.

**Code Details**:
_createServiceUrl()_
```
private ServiceURL createServiceUrl(String storageAccountName, String storageAccountKey, String endpointUrl, String endpointProtocol) throws InvalidKeyException, MalformedURLException {
    ServiceURL serviceURL = null;
    try {
        FlintLogger.JOB_LOGGER.info("createServiceUrl | Creating Service URL");
        FlintLogger.JOB_LOGGER.debug("createServiceUrl | Creating Service URL with inputs: \n"+storageAccountName+"\n"+storageAccountKey+"\n"+endpointUrl+"\n"+endpointProtocol);

        // Use your Storage account's name and key to create a credential object; this is used to access your account.
        SharedKeyCredentials credential = new SharedKeyCredentials(storageAccountName, storageAccountKey);
        FlintLogger.JOB_LOGGER.info("createServiceUrl | Storage credentials created "+credential.toString());

        /*
            Create a request pipeline that is used to process HTTP(S) requests and responses. It requires your accont
            credentials. In more advanced scenarios, you can configure telemetry, retry policies, logging, and other
            options. Also you can configure multiple pipelines for different scenarios.
         */
        HttpPipeline pipeline = StorageURL.createPipeline(credential, new PipelineOptions());
        FlintLogger.JOB_LOGGER.info("createServiceUrl | Created Http pipeline "+pipeline);

        /*
            From the Azure portal, get your Storage account blob service URL endpoint.
            The URL typically looks like this:
         */
        URL url = new URL(String.format(Locale.ROOT, endpointProtocol+"://%s.blob."+endpointUrl, storageAccountName));
        FlintLogger.JOB_LOGGER.debug("createServiceUrl | Created Url with specified endpoint "+url.toString());

        // Create a ServiceURL object that wraps the service URL and a request pipeline.
        serviceURL = new ServiceURL(url, pipeline);
        FlintLogger.JOB_LOGGER.debug("createServiceUrl | ServiceUrl structure: "+serviceURL.toURL().toString());


        FlintLogger.JOB_LOGGER.info("createServiceUrl | Created service URL");

    }catch(Exception e) {
        FlintLogger.JOB_LOGGER.error("createServiceUrl | Exception: ",e.getMessage());
    }
    return serviceURL;
}
```

_onRequest()_
```
// Create Service URL
            ServiceURL serviceUrl = createServiceUrl(storageAccountName, storageAccountKey, endpointUrl, endpointProtocol);
            FlintLogger.JOB_LOGGER.debug("onRequest | serviceUrl "+serviceUrl.toURL());
            FlintLogger.JOB_LOGGER.debug("onRequest | serviceUrl Before request"+serviceUrl.toURL());

            try {
            serviceUrl.listContainersSegment(null, new ListContainersOptions()).blockingGet().body().containerItems().forEach(container -> {
                FlintLogger.JOB_LOGGER.debug("onRequest | Blocking get : "+container.name());
            });
            }catch(Exception e) {
                FlintLogger.JOB_LOGGER.error("Error in thread blocking request ", e.getLocalizedMessage());
            }
```
### Have you found a mitigation/solution?
Not yet.

**Comment by rickle-msft** [comment]
Hi, @akash-infiverve. Thanks for posting this question. 

Before jumping into the actual issue, I will recommend that if you haven't already invested a significant amount of time into upgrading to v11, I would recommend you pause and stay on v8 for now. We have discovered some fundamental problems in the networking stack and we are working on overhauling it now. We will have a preview of the fix for these sorts of problems in a couple weeks. If you are ok not moving to v11 for now, feel free to ignore the rest of my response. 

If you have already made significant progress in adopting v11, I am happy to continue diagnosing the problem with you. I think the best place to start would be if you could explain a bit more about what you mean by your service class is a Vertex verticle. I don't know much about that and thus cannot immediately speak to what part of the different environment might cause the different behavior.

**Comment by akash-infiverve** [comment]
Hello, @rickle-msft 
Thanks for the reply! I was just in the initial stages of using this SDK so I have started to build the application on v8(sync).

However is there async requests functionality in v8 as we'll be requiring those?

**Comment by rickle-msft** [comment]
There's no async in v8, but we are actually set to preview a re-vamped version of the async stuff today. It'll be shipped under the groupId com.azure instead of com.microsoft.azure, so you'll be able to load it side-by-side with v8 and upgrade as you see fit (i.e. whatever work you're doing now isn't necessarily lost as you can upgrade it when you choose). Just to rattle off some benefits: It'll have sync and async options that coexist well and abide by similar interfaces. It'll have a much more stable networking stack. It's using Reactor instead of Rx, which is generally a much more mature and modern project. 

That said, it'll be preview one, so there are still a few elements of the design that we're discussing, and still a few features to bring over from both v8 and v10, but we're moving quickly towards bringing together the best of both those previous efforts.

**Comment by rickle-msft** [comment]
Hello, as an update, we have released preview 2 of v12, which has async support, if you are still interested in taking a look. If you are happy on v8, then by all means feel free to stay.

I am going to close this issue as I believe it has been resolved, but please feel free to reopen it or otherwise continue to engage if you need further support.
