### ISSUE TITLE
List blob names only

### ISSUE THREAD

**Issue by ikryvorotenko** [Azure/azure-storage-java#480]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
v11

### What problem was encountered?
I have a functionality which is looping over all blobs in container, so I list the blobs and then work with each blob. So in order to loop over blobs I just need their names.

The issue here is that the method `listBlobsFlatSegment` returns blobs with Properties, which i'd like to avoid for sake of performance.

### Have you found a mitigation/solution?
Nope. I just started migrating from v8 to v11. As a side question, I'd like to clarify what's going on with versioning and is there a blob client roadmap documented anywhere? I saw there's a blob api v12.preview in source code (https://github.com/Azure/azure-sdk-for-java/tree/master/storage/client/blob), which has slightly different API. And I saw the reply here suggesting not to migrate to V11 (https://github.com/Azure/azure-storage-java/issues/477#issuecomment-506824421). Please clarify when it'd be the best case to start migration.

**Comment by rickle-msft** [comment]
Hi, @ikryvorotenko. Thank you for posting this question. It turns out that the [REST Api](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs) always returns blob properties and there is not an option to disable this behavior. This was also the behavior in v8. I don't know that there is a great way to optimize that performance because we'd have to scan the entire xml document including the properties even if we decided not to deserialize them. Your best bet is to just ignore the properties. We would be open to discussing any suggestions you have on the matter, though.

As far as guidance for versioning, we are hoping to publish a document about that soon. In short, you are fine to stay on v8 for the foreseeable future as we are still supporting and developing it. We are going to stop development in v11 in favor of v12. Unfortunately, the introduction of v12 means that the async offerings are being reset to preview for the time being, Since v12 contains both sync and async apis, v12 is the long term strategy for our sdk; New features will ultimately be added to v12 first, and v12 will live past v8's eventual deprecation whenever that may be. We would love to have you try out v12 and give us feedback, especially since you should be able to load v8 and v12 side by side, but we also understand if you have urgent business reasons that require you to stick with the stable v8.

**Comment by ikryvorotenko** [comment]
@rickle-msft thanks for the clarifications. 

I played with v12 API and it looks pretty nice, despite of documentation lack. Also, I noticed that examples on README page are out of date, just fyi.

I faced the issue with streaming data into blobs, as `upload` method requires the size of blob in advance, so I'm wondering if streaming is something planned to be supported?

**Comment by rickle-msft** [comment]
@ikryvorotenko thank you for the feedback! We are definitely planning to bulk up the documentation pretty heavily and fix up the samples in successive previews. 

I mentioned this on the other issue you opened, but we do have support for BlobInputStream and BlobOutputStream in v12, so you can use those options if you don't know the length. We also haven't ported this forward from v11 yet, but there will be a method that takes a Flux of unknown length and uploads that as well. That will be in before GA.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe it has been resolved, but please feel free to reopen it or otherwise continue to engage if you need further support.

PS The PR for the feature I mentioned about uploading without a known length in async scenarios can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/4935). I have a bit more work to do to merge it in, but it should be in by the next preview.
