### ISSUE TITLE
Using Input/Output streams with async blob api

### ISSUE THREAD

**Issue by ikryvorotenko** [Azure/azure-storage-java#482]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
v12

### What problem was encountered?
While migrating from v8 to v12, i faced an issue that v12 doesn't have an option to get input/output stream for blob.

Are there any options for streaming data from/to blobs? If yes, where I could get some examples?

For my specific case, I used OutputStream from v8 blob api to write blob as zip file, writing zip entries on the fly. How would I do that with v12 async api?
### Have you found a mitigation/solution?
Nope

**Comment by rickle-msft** [comment]
Hi, @ikryvorotenko. Thanks for your question. We actually did add [BlobOutputStream](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/client/blob/src/main/java/com/azure/storage/blob/BlockBlobClient.java#L98) and [BlobInputStream](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/client/blob/src/main/java/com/azure/storage/blob/BlobClient.java#L138) back into v12 as a part of putting sync apis alongside the async apis. These options are only sync because of the nature of streams. 

If you want an async solution to this, the way to do this is creating a Flux with your data to zip as the source of your Flux. Fluxes cover both the input and output scenarios in the reactive world, which is why we don't have a specific offering for it. If you want more support in how to create this async workflow, we'd be happy to work with you on that.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe it has been resolved, but please feel free to reopen it or otherwise continue to engage if you need further support.
