### ISSUE TITLE
how to list blobs with marker in V12 using java

### ISSUE THREAD

**Issue by patitapaban19** [Azure/azure-storage-java#501]
### Which service(blob, file, queue, table) does this issue concern?
Listing blobs

### Which version of the SDK was used?
Please note that if your issue is with v11, we are recommending customers either move back to v11 or move to v12 (currently in preview) if at all possible. Hopefully this resolves your issue, but if there is some reason why moving away from v11 is not possible at this time, please do continue to ask your question and we will do our best to support you. The README for this SDK has been updated to point to more information on why we have made this decision. 

### What problem was encountered?
In V11 there was support for downloading blobs using marker but in V12.0.0-preview.3 i feel that option is not available

### Have you found a mitigation/solution?
No

**Comment by rickle-msft** [comment]
@patitapaban19 thank you for posting your question. With preview 3 came the introduction of the PagedFlux/PagedIterable types. These are lazy types that will fetch data as requested. They also have the option of emitting/iterating over individual elements or over pages of elements. If you want to list using a marker, you can call the byPage(String) method, though you should note that starting from a marker does require your listing operation to process pages instead of individual elements.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe the question has been sufficiently addressed. Please reopen the issue or post a follow up if you need more support.
