### ISSUE TITLE
Query with take(5) returning more than 50 items

### ISSUE THREAD

**Issue by devseshu** [Azure/azure-storage-java#62]
TableQuery<Product> partitionQuery = TableQuery.from(Product.class)
				.where(combinedFilter).take(size);

Take is returning more items. Please let me know if there is any issue with this. I am using azure-storage-4.0.0.jar

**Comment by devseshu** [comment]
To give more context: 

for (Product entity : cloudTable.execute(partitionQuery)) {
 // Some business logic
		}

Where as executeSegmented respects take parameter?

**Comment by emgerner-msft** [comment]
I think what you’re expecting will happen if you use executeSegmented instead of execute. executeSegmented will execute a single query to the service and return you a ResultSegment<T> with everything returned. This segment will contain up to 5 (your take count) responses which you can access via it’s getResults method. Note that even if there are 5 results on the service executeSegmented may return less than that and give you a continuation token which you must follow to get the rest.

execute returns an Iterable<T>. The where/select work exactly the same here, but take count doesn’t really make sense because the iterable will simply query the service for more results when you ask for more. All take count does here is ask the service only for the next 5 entities each time it asks the service for more. 

I would recommend taking a look in Fiddler to demonstrate the above points. You can see executeSegmented will only make one request whereas execute will make multiple service requests (at least for your code below). Both will correctly include the take count limit of 5 in each service request.

So, using execute is nice since it follows continuation tokens for you, but it will keep getting results as long as you keep asking for more (which currently is what your for-loop does). If you make a for-loop that only iterates over the first 5 elements that should solve your issue and stop execute from making extra requests and returning extra results.

**Comment by emgerner-msft** [comment]
Closing as this seems resolved and hasn't had any recent activity. Feel free to reopen with any follow up questions or open a new issue with any additional questions!
