### ISSUE TITLE
How can I tell the number of bytes written to storage?

### ISSUE THREAD

**Issue by piascikj** [Azure/azure-storage-java#64]
I'm using BlobOutputStream to write chunked http requests to a BlockBlob.  I need to know when the operation is finished, but the only thing I can seem to track is when a request completes with StorageEventMultiCaster.

**Comment by emgerner-msft** [comment]
Could you clarify a bit further? Do you need to know when the entire blob is pushed or on a per-read level?

**Comment by piascikj** [comment]
Just when the entire blob is pushed.

**Comment by emgerner-msft** [comment]
Since there is some client side buffering (see getStreamWriteSizeInBytes, default is 4MB), not all data may actually be written until the stream is closed or flush is called. If you call flush or close the stream and wait for the method to complete you can guarantee everything was pushed. 

Note: If you're not using any aspect of BlobOutputStream where you need to handle the stream itself, the upload* methods will probably be faster. These methods allow parallelism which will help if you're using large blobs (see ConcurrentRequestCount on BlobRequestOptions) and can do chunking more optimally since they know they're doing the full upload at once. If you need to play with the stream by all means use BlobOutputStream, just wanted to make sure you have the full picture.

**Comment by piascikj** [comment]
I definitely want the `BlobOutputStream` and it works great for what I'm doing.  (Upload to myservice -> Upload to azure) I just hoped there was a way to find out how many bytes were uploaded with `StorageEventMultiCaster<RequestCompletedEvent, StorageEvent<RequestCompletedEvent>>`.  At the moment I'm calculating the upload bytes in `eventOccurred(RequestCompletedEvent event)` by checking to make sure the request was a post, then adding the StreamWriteSizeInBytes to my total until it goes over the actual content-length that was sent to my server.

**Comment by emgerner-msft** [comment]
Okay, since I can't see the code I'm not sure of the use case. :) Always just want to make sure folks are aware of the options available.

I think to help further I'll probably just need a code snippet or a little more info on what your code looks like. If you're looking for total, why is the content-length sent to your server not correct? Or, when you call write on the stream why can you not sum the data length there? I'm sure there's good reasons but without knowing more I'm not sure how many ideas I can generate.

**Comment by emgerner-msft** [comment]
Closing as I didn't hear back in a couple months. If you want to continue the discussion, feel free to reopen with some of the details requested above and we can continue to work on this!
