### ISSUE TITLE
Table storage - reflection on methods skipping boolean fields

### ISSUE THREAD

**Issue by uded** [Azure/azure-storage-java#68]
In the use case where I have a `boolean` field in the class extending `TableServiceEntity` with no setter, the field will be skipped. The problem is that the convention for `boolean` getter is to prefix the method with `is` rather than `get`, while the `generatePropertyPairsHelper` is using a hard coded prefixes to decide whether the field should be included or not in the value pairs.

The problematic bit of the code:

``` java
if (m.getName().length() < 4 || (!m.getName().startsWith("get") && !m.getName().startsWith("set"))) {
    continue;
}
```

Furthermore, `PropertyPair.shouldProcess()` method is skipping fields which do not have getter with a prefix `get` and setter with a prefix `set`.

While I do not consider this to be the best option in the first place - to use reflection rather than annotations for example - this hardcoded approach seems to be a wrong one. Wouldn't it better to get a list of fields via reflection as well? In the end assuming that the class will only use getter and setters with only those two prefixes is ultimatively faulty as one can use a logic-bound constructor, different method names or skip those methods altogether and use public/package for fields...

**Comment by emgerner-msft** [comment]
As in the other post, thanks for following up! Since there's several questions here I'll address them in sections.

1. Wouldn't it better to get a list of fields via reflection as well? 
>> The main reason we don't do this is that a lot of folks have logic around what they want to store that may be different than the fields in their class. For example, a class containing a private field with a customers social security number might have logic to hash and salt that field in the getter. Methods provide a lot more flexibility that a lot of folks absolutely need.

2. While I do not consider this to be the best option in the first place - to use reflection rather than annotations for example
>> As I'm sure you realize, using annotations requires reflection within itself. We do already use some annotations to modify the base behavior (@Ignore and @StoreAs) but having a good, simple base case that works for a lot of folks without annotations is important to use. This is why we have some logic which works on unannotated methods.

3. Getters/Setters Prefixing
>> I completely agree that the getters/setters naming route is somewhat inflexible. For the reason mentioned above though, we do want to use methods. We also want to require there is a method to both get and set as we need to support both insert and query. The best route to allow more flexible method naming (ex 'is') for Booleans is probably annotations. My initial thought is that this will be non-breaking. This is something we can add to the backlog.

In the end while we do want to make the reflection based serialization good enough to be useful and we're happy to add some features as discussed above. I do want to note that we don't intend to build something the likes of [Jackson Annotations](https://github.com/FasterXML/jackson-annotations) -- a great lib by the way. The TableEntity interface with the writeEntity and readEntity methods are the intended method for folks with more complex needs.

**Comment by uded** [comment]
Ad 1:
Simple solution - provider a marshaller in the annotation so the folks can do whatever they desire with the value of that field.

Ad 2:
Yes, it was a shortcut. I meant that one should not rely purely on reflection scouting of methods/field names as it is right now.

Ad 3:
Well, is is inflexible and it's breaking convention. Simple workaround would be to check for methods prefixed with `is` as well with a double check if it is a boolean field/return.

Regarding this and #67 one can easily build a second, higher level solution on top of the current one working with annotations. Look what AWS did with DynamoDBMapper. Heck, if I am done with the current work I might just do that, since it is rather simple task in general...

**Comment by emgerner-msft** [comment]
If there's changes you have in mind we're happy to consider pull requests for non-breaking features with a quick chat. We're also happy to discuss pull requests for breaking features but as usual the more breaking, the less likely. Otherwise we'll mark these things down in the backlog and respond on either thread if we end up doing more.

**Comment by villeapvirtanen** [comment]
I would strongly advice to accept "is" as the prefix for boolean (primitive) getters. 

This is part of the JavaBeans specification, version 1.01, section 8.3.2, and the way java generally works.  The spec is dated 1997, so it's like been there for ever. (You can view the spec here: http://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/ accept license, download pdf.)

For convenience I've included the relevant section below:

> 8.3.2 Boolean properties
In addition, for boolean properties, we allow a getter method to match the pattern:
public boolean is<PropertyName>();
This “is<PropertyName>” method may be provided instead of a “get<PropertyName>” method,
or it may be provided in addition to a “get<PropertyName>” method.
In either case, if the “is<PropertyName>” method is present for a boolean property then we will
use the “is<PropertyName>” method to read the property value.
An example boolean property might be:
```
public boolean isMarsupial();
public void setMarsupial(boolean m);
```

At least it would be nice to get a warning, as it breaks the specification and really bites all seasoned devs that use primitive booleans. (And if one uses any tooling to generate the getter setter pairs it results broken implementation.)

**Comment by emgerner-msft** [comment]
We are planning on taking the 'is' fix, simply not several of the other suggestions in the initial post that more fundamentally change how table serialization is done and how folks use it. However, the change to accept 'is' is breaking -- new fields will be serialized that weren't before. So, we're waiting until we do our next breaking release.
