### ISSUE TITLE
Please refactor CloudBlobContainer to interface, or make class non-final

### ISSUE THREAD

**Issue by wolfgangmeyers** [Azure/azure-storage-java#77]
I'm trying to write unit tests for my java application code that interacts with the azure storage api. I don't want to actually make any api calls, so I'd like to create mock objects for the storage services. I'm using CloudBlobContainer to get references to CloudBlockBlob instances - but it looks like CloudBlobContainer is a final class (so I cannot mock the concrete class), and doesn't implement any interfaces (so I can't mock any interfaces either). Reasonable to ask that this class and others (like CloudBlockBlob) be marked as non-final for testing? Thanks!

**Comment by emgerner-msft** [comment]
The main reason we made these class final is because they are not fundamentally designed to be extended. The discussion in [this Stack Overflow question](http://stackoverflow.com/questions/218744/good-reasons-to-prohibit-inheritance-in-java) is a good summary. It's an acknowledged flaw that this can make mocking difficult. The thought on the storage side is that for many folks the [storage emulator](https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/) provides a better method of testing anyways since it's easy to sub in for prod storage, requires no mocking, works offline, etc. There are flaws with this as well, but I'm curious if you've considered using it instead?

**Comment by wolfgangmeyers** [comment]
I'm doing development and testing primarily on Mac OSX and Ubuntu linux, so I don't think running Microsoft SQL Server is an option. If opening the class to being extended is out (which I think is perfectly reasonable), can the functionality be expressed as an interface that is implemented by the concrete final class?

**Comment by emgerner-msft** [comment]
Fair enough for the Mac OSX side of thing. That's the main drawback of emulator. :) Opening the class to be extendable is far more likely to happen than interfaces because interfaces will result in a break of basically every API we have for existing users. This is out of the question. What framework are you using for mocking?

**Comment by wolfgangmeyers** [comment]
I've been using Mockito.

**Comment by emgerner-msft** [comment]
Got it. We'll consider un-finalizing, but in the mean time there's a couple pretty common solutions to consider that you can use without that change:
1. There are a bunch of mocking frameworks that don't require non-final methods, or that extend Mockito to not have those and other requirements. An example is [PowerMock](https://github.com/jayway/powermock)). 
2. You can use vanilla Mockito if you use the delegate pattern. Basically, you can make a class with an instance of the storage class you want to use and wrap only the methods you need. The disadvantage is boilerplate (solvable with stuff like [Lombok](https://projectlombok.org/features/Delegate.html)), the advantage is that you can very easily modify behavior or add methods with more custom business logic.

**Comment by wolfgangmeyers** [comment]
Thanks for pointing out PowerMock, I'll check it out.

**Comment by emgerner-msft** [comment]
Great, please tell us how that goes!

**Comment by emgerner-msft** [comment]
Any news here? Did PowerMock work out for you?

**Comment by wolfgangmeyers** [comment]
Yes, it did. Thanks for recommending it!

On Thu, Mar 10, 2016 at 2:49 PM Emily Gerner <notifications@github.com>
wrote:

> Any news here? Did PowerMock work out for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-storage-java/issues/77#issuecomment-195085233>
> .
>
-- 

Sent from my un-modded droid

**Comment by emgerner-msft** [comment]
Awesome! Good to hear. Closing this thread then.

**Comment by benjamin-bader** [comment]
Please reconsider this issue.  PowerMock is not suitable for our project, and it is not feasible for us to spin up a SQL Server instance for unit tests.

I recognize that these classes were marked final because they aren't designed to be extended; nevertheless, it seems to impose an undue amount of work on devs testing their interactions with Azure.  I don't think there is any harm in un-sealing the class and trusting developers with it.

**Comment by rrnair** [comment]
+1, I am also in trouble with unit testing Azure storage write. I am using Spock framework. I second the opinion of un-finalizing

**Comment by jofriedm-msft** [comment]
Hi @benjamin-bader and @rrnair , we have created an item in our backlog for this. Unfortunately, we have a large number of items in our backlog as well as currently focusing on other large-scale changes to our Java offering so I can't provide a timeline for when this change would be made. If either of you would like to contribute and add interfaces for the classes you need to mock you can also submit a PR.

**Comment by rrnair** [comment]
Thanks @jofriedm-msft, I tried setting up the dev environment, all the 1121 tests are failing in my machine. I am using IntelliJ/Mac. I know its not normal. Sorry to ask this question, but is there any documentation on dev setup, I didn't find any in the Contributor guidelines

**Comment by jofriedm-msft** [comment]
Hi @rrnair no problem. Thank you for offering to contribute! 😎 
We do have a [Contibuting.md](https://github.com/Azure/azure-storage-java/blob/master/CONTRIBUTING.md) if you didn't see this.
Are there any build errors? What are the errors the tests are failing with?
If you believe that requests are being made, you can use Fiddler for Mac which is a little buggy or CharlesProxy which has a license fee but offers a free trial

**Comment by rrnair** [comment]
Thanks @jofriedm-msft, I missed Contributing.md, there was no Compilation errors, tests were throwing Nullpointers since I had no idea about TestConfigurations.xml.

Now following Contributing.md and running tests with `TestConfigurations.xml`. I guess the `DevStore` Tenant is missing `<FileServiceEndpoint> node, I added that and tests are running at the moment, I will come back to you. 

Is there an email through which I can contact you, else I am bombarding with setup questions here. you could reach me at `ratheesh.ravi.nair@gmail.com`.

**Comment by jofriedm-msft** [comment]
Great! You can contact us at 'ascl at microsoft dot com'
