### ISSUE TITLE
Partition/Row keys changed when PUTting to the table storage

### ISSUE THREAD

**Issue by james-hu** [Azure/azure-storage-java#81]
Some characters in the partition and/or row key are "normalized" to other characters while generating the URLs for PUT requests for table storage insertOrReplace operations. Therefore an entity with the wrong partition and/or row key may be inserted. Below is a scenario to show this problem:
1. Insert a table entity with partition key "a" and row key "論"(U+F941)
2. Do a query on partition "a" and you will see one record
3. InsertOrReplace the same entity
4. Do a query on partition "a" and you will see two records, one with row key "論"(U+F941), another with row key "論"(U+8AD6)

Similar issue may exist for InsertOrMerge, query, and other operations as well.

To resolve, try to replace .toASCIIString() with something else at [line 64 of UriQueryBuilder class](https://github.com/Azure/azure-storage-java/blob/v4.0.0/microsoft-azure-storage/src/com/microsoft/azure/storage/core/UriQueryBuilder.java#L64)

For background, see [here](http://www.linkedin.com/pulse/%EF%A5%81-vs-%E8%AB%96-bugsissues-exposed-james-hu)

**Comment by emgerner-msft** [comment]
Thanks for the detailed background. Looking at that, this is definitely a bug in Java itself. Since the URI has to be ASCII, I don't see a very feasible workaround for storage to implement but I'll fiddle around. Have you submitted a bug to Oracle or should I? Have you run into any other characters I should point out to them?

**Comment by james-hu** [comment]
I suppose this is bug in JDK, however I don't think Oracle would actually fix it because this behaviour has been in JDK for a long time (at least since JDK6) and fixing this may break some other programs that depend on this behaviour. 

The easiest way to workaround is to modify [line 64 of UriQueryBuilder class](https://github.com/Azure/azure-storage-java/blob/v4.0.0/microsoft-azure-storage/src/com/microsoft/azure/storage/core/UriQueryBuilder.java#L64). You can create a customToAsciiString(URI uri) method and in that method either copy the code from JDK but remove [the use of "Normalizer.normalize(s, Normalizer.Form.NFC)"](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/java/net/URI.java#L2704), or use something like URLEncoder.encode(...) to do the escaping.

There are only three occurrences of  toASCIIString() in the main code: https://github.com/Azure/azure-storage-java/search?utf8=%E2%9C%93&q=toASCIIString%28%29

**Comment by emgerner-msft** [comment]
I'm looking at this closer and now I'm confused -- are you using Oracle Java (official) or OpenJDK? The code you linked to is OpenJDK. These are not the same, and we do not official support or test with OpenJDK.

**Comment by james-hu** [comment]
I am using Oracle JDK, but there is no reference of Oracle JDK source code on Internet, you can download source code from Oracle's website though.

The code in Open JDK is the same as in Oracle JDK. So I pasted that link for your reference.

**Comment by james-hu** [comment]
BTW, I've updated previous comment to include the bug review id I got from Oracle.
Even if Oracle admits this as a bug (not very likely), I still recommend applying a workaround in AzureStorageSDK because not everyone uses the latest JDK.

**Comment by emgerner-msft** [comment]
Okay good to hear -- wanted to make sure you were doing something supported. :) We definitely still need to work it out on our side no matter who owns the bug, but I do want to make sure Oracle is aware. 

We are not in any way, shape, or form legally allowed to copy code from that project per the [GNU license terms](https://en.wikipedia.org/wiki/GNU_General_Public_License). The logic isn't trivial anyways so it's probably unwise in any case.

The best work around is probably on a per-character basis which is why I ask if you've seen this in any other case.

**Comment by james-hu** [comment]
Haha I shouldn't have shown you the code. However, you can write your own code to implement the similar logic and functionality (It is just 30 lines of code there), or just use URLEncoder.encode(...). 

By saying "per-character", do you mean to enumerate through all the characters that are affected by Normalizer.normalize(s, Normalizer.Form.NFC)? That's not feasible. First I don't know the full set, you need someone who is expert in Unicode to give you the list, second there may be thousands or even tens of thousands of them. So please, don't try that.

**Comment by emgerner-msft** [comment]
Haha looking is fine, no problem. The method is indeed 30 lines long but it calls a couple thing:. ThreadLocalCoders.encoderFor (which I don't see publicly) and the Normalizer.normalize call. While the Normalizer messes up this particular character, it's probably there for a reason and other characters might be wrong. So if we make our own we need to commit to being Unicode experts as we take on the burden of testing all those characters (as well as understanding what those two methods do, and anything they call does). This is not something I think we can feasibly own in this library, for the reasons you mention. :)

So, I'd like to do a work around using the URLEncoder or toASCIIString. We've done testing with URLEncoder and ASCII chars, but not with unicode chars which is the concern. It actually had an issue which you can see the workaround for in [Utility.safeEncode](https://github.com/Azure/azure-storage-java/blob/v4.0.0/microsoft-azure-storage/src/com/microsoft/azure/storage/core/Utility.java#L717). Since toASCIIString has otherwise treated us well I'm not overly excited to move to URLEncoder unless there's several demonstrable problems that make it worth the testing burden and instability risk. My hope is if I have a char list, I can simply write a workaround for toASCIIString the way we did for URLEncoder.

**Comment by james-hu** [comment]
This [javadoc](https://docs.oracle.com/javase/7/docs/api/java/text/Normalizer.html) can help you understand what Normalizer.normalize(...) do and why it is not needed in our use case. You can also find Unicode related background information there

`ThreadLocalCoders.encoderFor("UTF-8").encode(CharBuffer.wrap(ns));` is just a cached version of `Charset.forName("UTF-8").newEncoder().encode(CharBuffer.wrap(ns))`  It caches the encoder in thread local. OpenJDK's implementation of ThreadLocalCoders can be found [here](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/nio/cs/ThreadLocalCoders.java)

**Comment by emgerner-msft** [comment]
Are you clear on why they used Normalizer at all in toASCIIString though? I do understand the doc, but I'm not clear on the usage you found. If you have thoughts I'd be interested.

I totally understand we can get into this sort of thing, but implementing a broken language feature inside a library not focused on it just seems like a recipe for bugs down the line. Why reimplement something we can easily wrap? Is there any issue you see with simply working around this particular character like we did in the place I linked to above? It seems like the least code and the least complexity.

**Comment by james-hu** [comment]
> Is there any issue you see with simply working around this particular character like we did in the place I linked to above?

That's not feasible. First I don't know the full set, you need someone who is expert in Unicode to give you the list, second there may be thousands or even tens of thousands of them. So please, don't try that.

**Comment by james-hu** [comment]
> Are you clear on why they used Normalizer at all in toASCIIString though?

No, I don't know. 
It doesn't matter. 
AzureStorageSDK creates two entities in Table Storage after a call to insert and another call to insertOrReplace using the same set of partition and row keys containing some unicode characters. This is not a correct behaviour. This matters.

**Comment by james-hu** [comment]
Did you follow the link in the javadoc to this page? http://www.unicode.org/reports/tr15/tr15-23.html

**Comment by emgerner-msft** [comment]
Wish I could respond more inline, but I'll do my best. :)

>> That's not feasible. First I don't know the full set, you need someone who is expert in Unicode to give you the list, second there may be thousands or even tens of thousands of them. So please, don't try that.

If it's not feasible to wrap, it's just as infeasible to write our own. If we write our own we have to test every character. If we wrap, we only fix characters we know are wrong and let the underlying implementation do the rest like in [Utility.safeEncode](https://github.com/Azure/azure-storage-java/blob/v4.0.0/microsoft-azure-storage/src/com/microsoft/azure/storage/core/Utility.java#L717).

>> No, I don't know. It doesn't matter. 

If we implement our own, we need to understand every detail of the base implementation. Otherwise like I said above: "While the Normalizer messes up this particular character, it's probably there for a reason and other characters might be wrong."

I completely agree the current behavior is wrong, but I don't think I quite see why you feel so strongly about the particular fix you're suggesting. Wrapping seems very simple and very testable to me. If we found more chars that were messed up, we'd simply add them. I'll sleep on it and we can discuss more tomorrow.

**Comment by james-hu** [comment]
> but I don't think I quite see why you feel so strongly about the particular fix you're suggesting

I suggested an implementation after you said "I don't see a very feasible workaround for storage to implement"

Then I pointed out that the original code in toASCIIString(...) has only 30 lines, after you said "The logic isn't trivial anyways'

I have never said anything like "must go my way". What I have been suggesting is "Your way won't work".
And I explained why the "Wrapping" way won't work - because the large number of characters that are affected.

>we only fix characters we know are wrong
> If we found more chars that were messed up
You can already know how to find all those wrong/more chars by following the rules on this page http://www.unicode.org/reports/tr15/tr15-23.html
Can they all be fixed? By have a huge table of characters-to-substitute?

Please note that in my original bug report, I mentioned "Some characters" rather than one particular character. Making a fix for U+F941 alone does not resolve the whole issue. There are so many characters affected by [UNICODE NORMALIZATION FORMS](http://www.unicode.org/reports/tr15/tr15-23.html)

**Comment by emgerner-msft** [comment]
Since it's been a bit, wanted to give a quick note that I am following up on this. In the process of investigating various fixes I found [another JDK bug](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8151244). This bug makes fixing this issue a lot harder since if we can't specify a pre-encoded path via this constructor to make a URI, we have to use the constructor that takes the entire URI string and doesn't handle any encoding. However, that means we have to find a way to appropriately encode everything manually (not just the path) and given each section of the URI has different encoding rules this makes things a lot harder.

**Comment by mirobers** [comment]
We don't have plans to directly address this issue in the library code, so I'm closing it.
