### ISSUE TITLE
GetBlobReference

### ISSUE THREAD

**Issue by JackMorris42** [Azure/azure-storage-java#84]
There is no method in `CloudBlobContainer` to retrieve a `CloudBlob` when we do not know its type (i.e. page, block...). The signature could be `public CloudBlob getBlobReference(String blobName)` like in azure-storage-net.

Thanks

**Comment by emgerner-msft** [comment]
If you make a blob of the wrong type, for example you make a CloudPageBlob when it's actually a block blob on the service, all of the methods that CloudPageBlob inherits from CloudBlob will still work. So, guessing actually works just fine. If you don't want to risk passing around something potentially the wrong type, simply set the variable to be of type CloudBlob. For example:
```java
CloudBlob blob = container.getBlockBlobReference(blobName)
```

The reason it's not totally simple on our end to make a getBlobReference method on CloudBlobContainer is that right now CloudBlob is abstract and thus can't be instantiated. We could make a CloudBlockBlob and return it as a CloudBlob and it would work fine (as discussed above), but we were worried this would be confusing because if the type were inspected that wouldn't make much sense. If you know for your particular application you're not going to be inspecting type (per the solution above), this is fine though to do on your side.

Finally, we could consider making CloudBlob a regular class rather than abstract, but given that it isn't a standard type on the service we were concerned this would be confusing. We know folks have occasionally gotten confused in other libraries (like .Net) that do this.

**Comment by JackMorris42** [comment]
I already tried but I got an exception when I called `downloadAttributes`. This method checks the blob type.

The `getBlobReference` method could do a remote call to find the type of the blob and then return the right class.

Another solution could be to have a `getBlobType` method in `CloudBlobContainer` and then call the right `get???BLobReference` method.

**Comment by emgerner-msft** [comment]
Ah, I tested with a couple APIs (ex download) but not in particular that one. Looking closer, everything except for that single one should succeed. :)

I don't want to have getBlobReference do a remote call and the others not -- especially since much of the time when folks are calling get*Reference they may not expect the blob to exist. This API would then work inconsistently with the other get*Reference APIs. However, with a slight rename this seems reasonable. I believe in some other languages we have get*ReferenceFromServer APIs. 

Overall, get*ReferenceFromServer seems more useful than getBlobType. I'm happy to add that in the next version. The method will return a CloudBlob and you'll have to cast into the correct subtype. However, this should be easy using instanceof or getBlobType on the blob properties object. 

Does this seem reasonable?

**Comment by JackMorris42** [comment]
This is perfect.

Thanks

**Comment by emgerner-msft** [comment]
Sounds good then. We have a version coming out today that it's a bit too late to get this into, but I'll make sure something comes out in the next one and at that point I'll update this thread.

**Comment by pemari-msft** [comment]
This is fixed as of our version 4.3.0 release. Please let us know if you have any further issues!
